Qa python homework 2
Amir0715/2020-2-Atom-QA-Python-A-Kamolov pull request #2
Opened 2020-10-11 21:42 UTC by Amir0715

# Домашнее задание №2

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
Были реализованны тесты на паттерне Pageobject
Были выполнены все пункты дз
Тесты запускаются на удаленном сервере селеноида на браузере хром 80 версии.

2020-10-16 01:08 UTC, snicks92 requested changes
Что то я попробовал всевозможные способы запуска и оно так и не запустилось
```
ImportError while importing test module '/Users/i.kirillov/lections/2020-2-Atom-QA-Python-A-Kamolov/hw2/code/tests/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_main.py:5: in <module>
    from some_fixtures import *
E   ModuleNotFoundError: No module named 'some_fixtures'
```

А так в остальном очень неплохая работа. Понравились тесты, их количество и как реализован PO. Не понравились локаторы. Надо поправить запуск, чтобы запускалось из консоли + комменты ниже

2020-10-16 01:08 UTC, snicks92 commented on hw2/code/tests/test_main.py
> +    # @pytest.mark.skip
лишние комменты

2020-10-16 01:08 UTC, snicks92 commented on hw2/code/ui/locators/locators.py
> +    BUTTON_AUTH_HEADER_LOCATOR = (By.XPATH, '/html/body/div[1]/div[1]/div[1]/div/div/div/div/div/div[2]/div/div[1]')
локаторы крайне плохие, это развалится через неделю

2020-10-16 01:08 UTC, snicks92 commented on hw2/code/ui/pages/base_page.py
> +        self.path_to_file='/home/amir-kamolov/photo/cat.jpg'
не будет работать так как например у меня на машине такого файла точно нет (и создавать его для тестов я не буду). надо добавить файл в репозиторий и правильно высчитать полный путь до него, относительно например текущего файла (`os.path.abspath(__file__)`)

2020-10-16 02:20 UTC, Amir0715 commented on hw2/code/ui/pages/base_page.py
> +        self.path_to_file='/home/amir-kamolov/photo/cat.jpg'
Да, вспомнил про это после пул реквеста.

2020-10-16 23:24 UTC, Amir0715 commented
@snicks92, исправил недочеты.

2020-10-17 12:55 UTC, snicks92 approved these changes

2020-10-17 12:55 UTC, snicks92 commented
Теперь ок. Балл сниму за то что сходу не запустилось и очень уж стремные локаторы.

2020-10-17 12:55 UTC, merged